### PR TITLE
fix(access.service): add restricting fields access

### PR DESCRIPTION
**Pull request by kvokov**
according to https://casl.js.org/v6/en/guide/restricting-fields
related to #254

### CODE REVIEW

**Comment by dzcpy** [comment]
Will it be merged?

**Comment by okonon** [comment]
It would be nice to merge this.

**Review by liquidautumn — APPROVED** [review]

**Comment by liquidautumn** [comment]
> @liquidautumn thanks a lot for your help!

Sorry it takes long, lots going on. I know this lib need some love, will try to work on pending issues asap.

**Comment by okonon** [comment]
@liquidautumn sounds good !

**Pull request merged**
